export const REGISTER_PROFILE = 'REGISTER_PROFILE'
export const GET_PROFILES = 'GET_PROFILES'
export const GET_PROFILES_SUCCESS = 'GET_PROFILES_SUCCESS'
export const GET_PROFILES_FAIL = 'GET_PROFILES_FAIL'
// get profil by id
export const GET_PROFILEBYID = 'GET_PROFILEBYID'
export const GET_PROFILEBYID_SUCCESS = 'GET_PROFILEBYID_SUCCESS'
export const GET_PROFILEBYID_FAIL = 'GET_PROFILEBYID_FAIL'
