export const REGISTER_PROFILE = 'REGISTER_PROFILE'
export const GET_PROFILES="GET_PROFILES"
export const GET_PROFILES_SUCCESS ="GET_PROFILES_SUCCESS"
export const GET_PROFILES_FAIL="GET_PROFILES_FAIL"