export const REGISTER_PROFILE = 'REGISTER_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const GET_PROFILES_SUCCESS = 'GET_PROFILES_SUCCESS';
export const GET_PROFILES_FAIL = 'GET_PROFILES_FAIL';
// get profil by id
export const GET_PROFILEBYID = 'GET_PROFILEBYID';
export const GET_PROFILEBYID_SUCCESS = 'GET_PROFILEBYID_SUCCESS';
export const GET_PROFILEBYID_FAIL = 'GET_PROFILEBYID_FAIL';
// TOGGLE
export const TOGGLE_TRUE = 'TOGGLE_TRUE';
export const TOGGLE_FALSE = 'TOGGLE_FALSE';
// edit profile
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAIL = 'EDIT_PROFILE_FAIL';
// delete profile
export const DELETE_PROFILEBYID = 'DELETE_PROFILEBYID';
export const DELETE_PROFILEBYID_SUCCESS = 'DELETE_PROFILEBYID_SUCCESS';
export const DELETE_PROFILEBYID_FAIL = 'DELETE_PROFILEBYID_FAIL';
