export const LOAD_RESERVATION = "LOAD_RESERVATION";
export const ADD_RESERVATION = "ADD_RESERVATION";
export const FAIL_RESERVATION = "FAIL_RESERVATION";

export const GET_REQUEST_RESERVATION = "GET_REQUEST_RESERVATION";
export const GET_ACCEPTED_RESERVATION = "GET_ACCEPTED_RESERVATION";

export const ACCEPT_RESERVATION = "ACCEPT_RESERVATION";
export const DECLINE_RESERVATION = "DECLINE_RESERVATION";
